providers = ["go"]

[phases.setup]
aptPkgs = ["libvips", "libvips-dev"]

[phases.install]
cmds = ["go mod download"]

[phases.build]
cmds = ["go build -C cmd/app -o out"]

[phases.start]
cmd = "./out"