providers = ["...","go"]

[phases.setup]
aptPkgs = ["...", "libvips", "libvips-dev"]

[phases.install]
cmd = "go mod download"

[phases.build]
cmd = "go build -C cmd/app -o out"

[phases.start]
cmd = "./out"