[build]
builder = "NIXPACKS"
buildCommand = "go build -C cmd/app -o out"

[build.phases.setup]
aptPkgs = ["libvips", "libvips-dev"]

[build.phases.install]
dependsOn = ["setup"]
cmds = ["go mod download"]

