[build]
builder = "NIXPACKS"
buildCommand = "CGO_ENABLED=1 && go build -C cmd/app -o out"

[build.phases.setup]
nixPkgs = ["...", "libgcc"]
aptPkgs = ["libvips", "libvips-dev"]

[build.phases.install]
dependsOn = ["setup"]
cmds = ["whereis gcc"]

